# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_team_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='picture',
            field=models.CharField(default='', max_length=300),
        ),
    ]
